data:
  train:
    images_dir: "./ffhq_8k_split/train"
    batch_size: 16

  valid:
    images_dir: "./ffhq_8k_split/val"
    batch_size: 16

training:
  epochs: 50
  device: "cuda:0"

  optimizer:
    lr: 0.0001


model:
  model_checkpoint: "./src/edsr64_x4.pt"