data:
  train:
    images_dir: "./ffhq_8k_split/train"
    batch_size: 16

  valid:
    images_dir: "./ffhq_8k_split/val"
    batch_size: 16

  test:
    images_dir: "./ffhq_8k_split/test"
    batch_size: 16

training:
  model_size: "large"
  scale: 4
  epochs: 50
  device: "cuda:0"
  combined_loss: False
  optimizer:
    lr: 0.0001


model:
  pre_trained: False
  train_from_x2: False
  model_checkpoint: "./src/edsr_x4.pt"